version: '3.4'

services:
  notes.api:
    container_name: notes.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - IdentityUrl=http://identity.api
      - ConnectionString=${MONKEYNOTE_AZURE_NOTES_DB:-Server=sql.data;Database=RocketMonkey.Monkeynote.Services.NotesDb;User Id=sa;Password=Passw0rd!;MultipleActiveResultSets=true}
    ports:
      - "5210:80"
    depends_on:
      - sql.data
    networks:
      - backend

  ocelotapigwweb:
    container_name: web.bff
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - IdentityUrl=http://identity.api
    volumes:
      - ./src/ApiGateways/Web.Bff:${MONKEYNOTE_OCELOT_VOLUME_SPEC:-/app/configuration}
    ports:
      - "5200:80"

  sql.data:
    container_name: sql.data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd!
    ports:
      - "27017:1433"
    networks:
      - backend

  identity.api:
    container_name: identity.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${MONKEYNOTE_AZURE_IDENTITY_DB:-Server=sql.data;Database=RocketMonkey.Monkeynote.Services.UserDb;User Id=sa;Password=Passw0rd!;MultipleActiveResultSets=true}
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5310:80"
    networks:
      - backend
    depends_on:
      - sql.data

  webspa:
    container_name: webspa
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "4300:80"

networks:
  backend:
    driver: bridge

